# Generated by Django 3.0.7 on 2020-09-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
